name: Python package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Setup Environment Variables
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "NUITKA_CACHE_DIR=${{ github.action_path }}/nuitka/cache"
          $pythonVersion = (python --version 2>&1).Split(' ')[1] -replace '\.(\d+)$', '.$1'
          Add-Content -Path $env:GITHUB_ENV -Value "PYTHON_VERSION=$pythonVersion"

      - name: Cache Nuitka cache directory
        uses: actions/cache@v3
        with:
          path: ${{ env.NUITKA_CACHE_DIR }}
          key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-nuitka-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-
            ${{ runner.os }}-python-
            ${{ runner.os }}-

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt

      - name: Build package
        shell: pwsh
        run: |
          python build.py

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.exe
